### ISSUE TITLE
Backwards-incompatible change in 1.6.0 causes NullPointerException

### ISSUE THREAD

**Issue by staktrace** [awslabs/dynamodb-streams-kinesis-adapter#57]
Hi, we have some code that invokes `StreamsWorkerFactory.createDynamoDbStreamsWorker` like so:
```
StreamsWorkerFactory.createDynamoDbStreamsWorker(
      /* recordProcessorFactory = */
      transactionAuthRequestsStreamsRecordProcessorFactory,
      /* config = */
      kinesisClientLibConfiguration,
      /* streamsClient = */
      amazonDynamoDBStreamsAdapterClient,
      /* dynamoDBClient = */
      dynamoDBClient,
      /* cloudWatchClient = */
      null
)
```

In version 1.5.3 of this lib, this worked fine. In 1.6.0 it throws an NullPointerException with this at the top of the stack:
```
java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "cloudWatchClient" is null
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker.getMetricsFactory(Worker.java:1241)
	at com.amazonaws.services.dynamodbv2.streamsadapter.StreamsWorkerFactory.createDynamoDbStreamsWorker(StreamsWorkerFactory.java:127)
```

It appears that passing a null cloudWatchClient is no longer allowed, is this intentional?

**Comment by staktrace** [comment]
https://github.com/awslabs/amazon-kinesis-client/blob/1.14.9/src/main/java/com/amazonaws/services/kinesis/clientlibrary/lib/worker/Worker.java#L1241 is the line that is generating the exception (I believe)
